language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer install --no-interaction

script:
    - ./vendor/bin/tester -s -p php ./tests/cases

after_failure:
    # Print *.actual content & log content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done
